INSERT INTO roles (name) VALUES ('ROLE_USER');
INSERT INTO roles (name) VALUES ('ROLE_ADMIN');
INSERT INTO roles (name) VALUES ('ROLE_MODER');
INSERT INTO roles (name) VALUES ('ROLE_SELLER');
INSERT INTO roles (name) VALUES ('ROLE_UP_SELLER');